import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body
        className={`${dmSans.variable} antialiased bg-slate-800 text-slate-200`}
        style={{ fontFamily: "var(--font-dm-sans)" }}
      >
        {children}
        <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}
